pos-web/src/main/java/com/jdc/pos/controller/EmployeeBean.java
package com.jdc.pos.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jdc.pos.entitty.Employee;
import com.jdc.pos.entitty.Employee.Role;
import com.jdc.pos.service.EmployeeService;

@Named
@ViewScoped
public class EmployeeBean implements Serializable{

	private static final long serialVersionUID = 1L;
	
	private String name;
	private Role role;
	
	private Employee employee;
	private List<Employee> list;
	
	@Inject
	private EmployeeService service;
	
	public void addNew() {
		employee = new Employee();
	}
	
	public void save() {
		service.save(employee);
		search();
	}
	
	public void editEmployee(Employee emp) {
		employee = emp;
	}
	
	public void search() {
		list = service.search(role, name);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public List<Employee> getList() {
		return list;
	}

	public void setList(List<Employee> list) {
		this.list = list;
	}

	public EmployeeService getService() {
		return service;
	}

	public void setService(EmployeeService service) {
		this.service = service;
	}
	
	public Role[] getRoles() {
		return Role.values();
	}

}

pos-web/src/main/java/com/jdc/pos/controller/PurchaseEditBean.java
package com.jdc.pos.controller;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jdc.pos.MessageHandler;
import com.jdc.pos.PosValidationException;
import com.jdc.pos.entitty.Invoice;
import com.jdc.pos.entitty.PaidHistory;
import com.jdc.pos.entitty.PurchaseItem;
import com.jdc.pos.entitty.PurchaseShop;
import com.jdc.pos.service.InvoiceService;
import com.jdc.pos.service.PurchaseShopService;

@Named
@ViewScoped
public class PurchaseEditBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Invoice invoice;
	private PurchaseShop shop;
	private PurchaseItem item;
	private PaidHistory paid;
	
	private List<PaidHistory> paidList;

	@Inject
	private InvoiceService service;

	@Inject
	private PurchaseShopService shopService;

	@PostConstruct
	private void init() {
		
		shop = new PurchaseShop();
		item = new PurchaseItem();
		paid = new PaidHistory();

		String str = FacesContext.getCurrentInstance().getExternalContext()
				.getRequestParameterMap().get("id");
		
		if(null != str && !str.isEmpty()) {
			long id = Long.parseLong(str);
			invoice = service.findById(id);
			
			paidList = service.findByInvoiceId(id);
			shop = invoice.getShop();
			
			calculate();
		}
		
		if(null == invoice) {
			invoice = new Invoice();
			paidList = new ArrayList<>();
		}
	}

	public void searchShop() {
		Optional<PurchaseShop> shopOption = shopService.findByName(shop.getName());
		shopOption.ifPresent(s -> shop = s);
	}

	public void addItem() {
		invoice.addItem(item);
		item = new PurchaseItem();
		calculate();
	}

	public void deleteItem(PurchaseItem item) {
		invoice.removeItem(item);
		calculate();
	}
	
	@MessageHandler
	public void addPaid() {
		
		if(paidList.stream().filter(a -> a.getId().getRefDate().equals(paid.getId().getRefDate())).findAny().isPresent()) {
			throw new PosValidationException("You already have paid in this day. Please select other day.");
		}
		
		LocalDate lastPaidDate = paidList.stream()
				.map(a -> a.getId().getRefDate())
				.sorted((a, b) -> b.compareTo(a))
				.findFirst().orElse(null);
		
		if(null != lastPaidDate && lastPaidDate.isAfter(paid.getId().getRefDate())) {
			throw new PosValidationException("Paid date must be greater than last paid date.");
		}
		
		paidList.add(paid);
		paid = new PaidHistory();
		calculate();
	}
	
	public void deletePaid(PaidHistory paid) {
		
		Iterator<PaidHistory> itr = paidList.iterator();
		
		while(itr.hasNext()) {
			PaidHistory old = itr.next();
			
			if(old.getId().equals(paid.getId())) {
				itr.remove();
				break;
			}
		}
		
		calculate();
	}
	
	private void calculate() {

		List<PaidHistory> temp = new ArrayList<>(paidList);
		paidList.clear();
		
		for(PaidHistory p : temp) {
			p.setLastRemain(getRemainAmount());
			paidList.add(p);
		}
		
		paid.setLastRemain(getRemainAmount());
	}

	public int getPaidAmount() {
		return paidList.stream().mapToInt(a -> a.getPaid()).sum();
	}
	
	public int getRemainAmount() {
		return (null == invoice.getTotal() ? 0 : invoice.getTotal()) - getPaidAmount();
	}

	public String save() {
		invoice.setShop(shop);
		service.save(invoice, paidList);
		return "/admin/purchases?faces-redirect=true";
	}

	public Invoice getInvoice() {
		return invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public PurchaseShop getShop() {
		return shop;
	}

	public void setShop(PurchaseShop shop) {
		this.shop = shop;
	}

	public PurchaseItem getItem() {
		return item;
	}

	public void setItem(PurchaseItem item) {
		this.item = item;
	}

	public PaidHistory getPaid() {
		return paid;
	}

	public void setPaid(PaidHistory paid) {
		this.paid = paid;
	}

	public List<PaidHistory> getPaidList() {
		return paidList;
	}

	public void setPaidList(List<PaidHistory> paidList) {
		this.paidList = paidList;
	}

}

pos-web/src/main/java/com/jdc/pos/controller/PurchaseShopBean.java
package com.jdc.pos.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jdc.pos.entitty.PurchaseShop;
import com.jdc.pos.service.PurchaseShopService;

@Named
@ViewScoped
public class PurchaseShopBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private String schTownship;
	private String schShopName;
	private String schContactPerson;
	
	private List<PurchaseShop> list;
	
	private PurchaseShop shop;
	
	@Inject
	private PurchaseShopService service;
	
	public void addNew() {
		shop = new PurchaseShop();
	}
	
	public void edit(PurchaseShop shop) {
		this.shop = shop;
	}
	
	public void search() {
		list = service.search(schTownship, schShopName, schContactPerson);
	}
	
	public void save() {
		service.save(shop);
		search();
	}

	public String getSchTownship() {
		return schTownship;
	}

	public void setSchTownship(String schTownship) {
		this.schTownship = schTownship;
	}

	public String getSchShopName() {
		return schShopName;
	}

	public void setSchShopName(String schShopName) {
		this.schShopName = schShopName;
	}

	public String getSchContactPerson() {
		return schContactPerson;
	}

	public void setSchContactPerson(String schContactPerson) {
		this.schContactPerson = schContactPerson;
	}

	public List<PurchaseShop> getList() {
		return list;
	}

	public void setList(List<PurchaseShop> list) {
		this.list = list;
	}

	public PurchaseShop getShop() {
		return shop;
	}

	public void setShop(PurchaseShop shop) {
		this.shop = shop;
	}
	
	

}

pos-web/src/main/java/com/jdc/pos/entitty/StockAction.java
package com.jdc.pos.entitty;

import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.InheritanceType.JOINED;

import java.io.Serializable;
import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.ManyToOne;

@Entity
@Inheritance(strategy = JOINED)
public abstract class StockAction implements Serializable {

	private static final long serialVersionUID = 1L;

	public StockAction() {
		security = new SecurityInfo();
		product = new Product();
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private long id;

	private LocalDate refDate;

	private Integer price;

	private Integer quentity;

	private SecurityInfo security;

	@ManyToOne
	private Product product;

	private Action action;
	
	public Integer getTotal() {
		
		if(null != price && null != quentity) {
			return price * quentity;
		}
		
		return null;
	}
	

	public enum Action {
		Sale,
		Purchase
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public LocalDate getRefDate() {
		return refDate;
	}

	public void setRefDate(LocalDate refDate) {
		this.refDate = refDate;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getQuentity() {
		return quentity;
	}

	public void setQuentity(Integer quentity) {
		this.quentity = quentity;
	}

	public SecurityInfo getSecurity() {
		return security;
	}

	public void setSecurity(SecurityInfo security) {
		this.security = security;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Action getAction() {
		return action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

}

pos-web/src/main/webapp/admin/categories.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://java.sun.com/jsf/html">

	<ui:composition template="/WEB-INF/template.xhtml">
	
		<ui:define name="content">
			
			<!-- Search -->
			<div class="ui segment">
				<h3><i class="tags icon"></i> Category Management</h3>

				<h:form styleClass="ui form" id="searchForm">
				
				<div class="inline fields">
					<div class="field">
						<label>Name</label>
						<h:inputText value="#{categoryBean.name}" p:placeholder="Enter Name" />
					</div>
					
					<h:commandLink styleClass="ui icon button" actionListener="#{categoryBean.search()}">
						<i class="search icon"></i> Search
						<f:ajax execute="@form" render="dataTable" ></f:ajax>
					</h:commandLink>
	
					<h:commandLink styleClass="ui icon blue button">
						<i class="plus icon"></i> Add New
						<f:ajax execute="@this" render="editTitle editForm" listener="#{categoryBean.addNew()}" onevent="showDialog()"></f:ajax>
					</h:commandLink>
				
				</div>
				
				</h:form>
			</div>
			
			<!-- Table -->
			<h:form id="dataTable">
				
				<h:dataTable value="#{categoryBean.list}" var="c" styleClass="ui table">
					
					<h:column>
						<f:facet name="header">ID</f:facet>
						<h:commandLink actionListener="#{categoryBean.edit(c)}" value="#{c.id}" >
							<f:ajax execute="@this" render="editTitle editForm" onevent="showDialog()"></f:ajax>
						</h:commandLink>
					</h:column>
					
					<h:column>
						<f:facet name="header">Name</f:facet>
						#{c.name}
					</h:column>
					
				</h:dataTable>
				
			</h:form>
			
			<!-- Edit Form -->
			<div class="ui tiny modal">
				
				<div class="header">
					<h3><h:outputText id="editTitle" value="#{empty categoryBean.category.id ? 'Add' : 'Edit'}" /> Category</h3>
				</div>
				
				<div class="content">
					
					<h:form id="editForm" styleClass="ui form">
						
						<div class="field">
							<label>Name</label>
							<h:inputText value="#{categoryBean.category.name}" p:placeholder="Enter Name" />
						</div>
						
						<h:commandLink styleClass="ui blue button" actionListener="#{categoryBean.save()}">
							<i class="save icon"></i> Save
							<f:ajax execute="@form" render="@form dataTable messages" onevent="hideDialog()"></f:ajax>
						</h:commandLink>
					</h:form>
					
				</div>
			
			</div>
					
		</ui:define>
	
	</ui:composition>
</html>

pos-web/src/main/webapp/admin/employees.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://java.sun.com/jsf/html">

	<ui:composition template="/WEB-INF/template.xhtml">
	
	
		<ui:define name="content">
			
			
			<div class="ui segment">

				<h3><i class="users icon"></i> Employee Management</h3>

				<!-- Search -->
				<h:form id="searchForm" styleClass="ui form">
					
					<div class="inline fields">
						
						<!-- Role -->
						<div class="field">
							<label>Role</label>
							<h:selectOneMenu styleClass="ui search dropdown" value="#{employeeBean.role}" >
								<f:selectItems value="#{employeeBean.roles}" var="r" itemLabel="#{r}" itemValue="#{r}"></f:selectItems>
							</h:selectOneMenu>
						</div>
						
						<!-- Name -->
						<div class="field">
							<label>Name</label>
							<h:inputText value="#{employeeBean.name}" />
						</div>
						
						<!-- Search Button -->
						<h:commandLink styleClass="ui icon button" actionListener="#{employeeBean.search()}" >
							<i class="search icon"></i> Search
							<f:ajax execute="@form" render="listForm script"></f:ajax>
						</h:commandLink>
						
						<!-- Add Button -->
						<h:commandLink styleClass="ui icon blue button" >
							<i class="plus icon"></i> Add New
							<f:ajax execute="@this" render="editForm script formTitle" onevent="showDialog()" listener="#{employeeBean.addNew()}" ></f:ajax>
						</h:commandLink>
						
					
					</div>
				
				</h:form>
			</div>


			<!-- Table -->
			<h:form id="listForm">
				<h:dataTable styleClass="ui table" value="#{employeeBean.list}" var="emp">
					<h:column>
						<f:facet name="header">Code</f:facet>
						<h:commandLink actionListener="#{employeeBean.editEmployee(emp)}" value="#{emp.loginId}" >
							<f:ajax execute="@this" render="editForm script formTitle" onevent="showDialog()"></f:ajax>
						</h:commandLink>
					</h:column>
	
					<h:column>
						<f:facet name="header">Name</f:facet>
						#{emp.name}
					</h:column>
	
					<h:column>
						<f:facet name="header">Role</f:facet>
						#{emp.role}
					</h:column>
	
					<h:column>
						<f:facet name="header">Phone</f:facet>
						#{emp.contact.phone}
					</h:column>
	
					<h:column>
						<f:facet name="header">Email</f:facet>
						#{emp.contact.email}
					</h:column>
					
				</h:dataTable>	
			</h:form>
					
			<!-- Pop Up -->
			<div class="ui small modal">
			
				<div class="header">
					<h3><h:outputText id="formTitle" value="#{empty employeeBean.employee.loginId ? 'Add' : 'Edit'}" /> Employee</h3>
				</div>
			
				<div class="content">
					<h:form id="editForm" styleClass="ui form">
						<div class="fields">
							<div class="six wide field">
								<label>Employee Name</label>
								<h:inputText p:placeholder="Enter Name" value="#{employeeBean.employee.name}" />
							</div>
							<div class="six wide field">
								<label>Role</label>
								<h:selectOneMenu styleClass="ui search dropdown" value="#{employeeBean.employee.role}">
									<f:selectItems value="#{employeeBean.roles}" var="r" itemValue="#{r}" itemLabel="#{r}" />
								</h:selectOneMenu>
							</div>
							<div class="four wide field">
								<label>Employee Code</label>
								<h:inputText readonly="#{not empty employeeBean.employee.loginId}" p:placeholder="Enter Code" value="#{employeeBean.employee.loginId}" />
							</div>
						</div>
						
						<div class="fields">
							<div class="six wide field">
								<label>Phone</label>
								<h:inputText p:placeholder="Enter Phone" value="#{employeeBean.employee.contact.phone}" />
							</div>
							<div class="ten wide field">
								<label>Email</label>
								<h:inputText p:placeholder="Enter Email" value="#{employeeBean.employee.contact.email}" />
							</div>
						</div>
						
						<div class="fields">
							<div class="six wide field">
								<label>Township</label>
								<h:inputText p:placeholder="Enter Township" value="#{employeeBean.employee.contact.township}" />
							</div>
							
							<div class="ten wide field">
								<label>Address</label>
								<h:inputText p:placeholder="Enter Street Address" value="#{employeeBean.employee.contact.address}" />
							</div>
						</div>
						
						<h:commandLink styleClass="ui primary active button" >
							<f:ajax execute="editForm" render="editForm listForm messages" listener="#{employeeBean.save()}" onevent="hideDialog()"></f:ajax>
							<i class="save icon"></i> Save
						</h:commandLink>
					</h:form>
				</div>
				
			</div>
			
			
		</ui:define>
		
	</ui:composition>
</html>

pos-web/src/main/webapp/admin/home.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://java.sun.com/jsf/html">

	<ui:composition template="/WEB-INF/template.xhtml">
	</ui:composition>
</html>

pos-web/src/main/webapp/admin/purchase-edit.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://java.sun.com/jsf/html">

	<ui:composition template="/WEB-INF/template.xhtml">

		<ui:define name="title">
			<h3>Invoice Registration</h3>
		</ui:define>
		
		<ui:define name="content">
			
			<h:form styleClass="ui form">
				<!-- Shop Info -->
				<div class="ui grid">
					
					<div class="twelve wide column">
						<div class="ui vertical segment">						
							<div class="ui header"><i class="icon building outline"></i> Shop Info</div>
							
							<div class="content">
								

								<div class="fields">
									<!-- Shop Name -->
									<div class="eight wide field">
										<label>Shop Name</label>
										<div class="ui action input">
											<h:inputText id="shopName" value="#{purchaseEditBean.shop.name}" p:placeholder="Enter Shop Name" />
											<h:commandLink actionListener="#{purchaseEditBean.searchShop()}" styleClass="ui red icon button" >
												<i class="icon search"></i>
												<f:ajax execute="shopName" render="@form script messages" />
											</h:commandLink>
										</div>
									</div>
									
									<!-- Contact Person -->
									<div class="eight wide field">
										<label>Contact Person</label>
										<h:inputText value="#{purchaseEditBean.shop.contactPerson}" p:placeholder="Enter Contact Person"/>
									</div>
								</div>
								
								<div class="fields">
									<!-- Phone -->
									<div class="eight wide field">
										<label>Phone Number</label>
										<h:inputText value="#{purchaseEditBean.shop.contact.phone}" p:placeholder="Enter Phone Number" />
									</div>
									
									<!-- Email -->
									<div class="eight wide field">
										<label>Email Address</label>
										<h:inputText value="#{purchaseEditBean.shop.contact.email}" p:placeholder="Enter Email Address"/>
									</div>
								</div>

								<div class="fields">
									<!-- Township -->
									<div class="six wide field">
										<label>Township</label>
										<h:inputText value="#{purchaseEditBean.shop.contact.township}" p:placeholder="Enter Township" />
									</div>
									
									<!-- Address -->
									<div class="ten wide field">
										<label>Address</label>
										<h:inputText value="#{purchaseEditBean.shop.contact.address}" p:placeholder="Enter Email Address"/>
									</div>
								</div>
							</div>
						</div>
						
						<!-- Purchase Item -->
						<div class="ui vertical segment">
		
							<div class="ui header"><i class="icon shop"></i> Purchase Items</div>

							<!-- Add Purchase Item -->
							<div class="fields">
								
								<!-- Category -->
								<div class="field">
									<label>Category</label>
									<h:selectOneMenu id="itemCategory" styleClass="ui dropdown" value="#{purchaseEditBean.item.product.category}" converter="#{categoryConverter}">
										<f:selectItems value="#{categories}" var="c" itemLabel="#{c.name}" itemValue="#{c}" />
									</h:selectOneMenu>
								</div>
								
								<!-- Name -->
								<div class="field">
									<label>Name</label>
									<h:inputText id="itemName" value="#{purchaseEditBean.item.product.name}" p:placeholder="Name"/>
								</div>
								
								<!-- Unit Price -->
								<div class="field">
									<label>Unit Price</label>
									<h:inputText id="itemUnitPrice" value="#{purchaseEditBean.item.price}" p:placeholder="Unit Price">
										<f:ajax execute="@this" render="itemTotalPrice" />
									</h:inputText>
								</div>
								
								<!-- Count -->
								<div class="field">
									<label>Count</label>
									<h:inputText id="itemQuentity" value="#{purchaseEditBean.item.quentity}" p:placeholder="Count">
										<f:ajax execute="@this" render="itemTotalPrice" />
									</h:inputText>
								</div>
								
								<!-- Price -->
								<div class="field">
									<label>Price</label>
									<h:inputText id="itemTotalPrice" readonly="true" value="#{purchaseEditBean.item.total}" p:placeholder="Price"/>
								</div>
								
								<!-- Add Button -->
								<div class="field">
									<div class="formButton" />
									<h:commandLink styleClass="ui icon red button" >
										<i class="icon plus cart"></i>
										<f:ajax execute="itemCategory itemName itemUnitPrice itemQuentity" render="@form script messages" listener="#{purchaseEditBean.addItem()}" />
									</h:commandLink>
								</div>
							
							</div>					
							
							<!-- Item Table -->			
							<h:dataTable styleClass="ui table segment" value="#{purchaseEditBean.invoice.items}" var="item" >
								
								<h:column>
								<f:facet name="header">Item</f:facet>
								<h:outputText value="#{item.product.name}" />
								</h:column>
							
								<h:column>
									<f:facet name="header">Category</f:facet>
									<h:outputText value="#{item.product.category.name}" />
								</h:column>
		
								<h:column>
									<f:facet name="header">Unit Price</f:facet>
									<h:outputText value="#{item.price}" />
								</h:column>
		
								<h:column>
									<f:facet name="header">Count</f:facet>
									<h:outputText value="#{item.quentity}" />
								</h:column>
		
								<h:column>
									<f:facet name="header">Price</f:facet>
									<h:outputText value="#{item.total}" />
								</h:column>
		
								<h:column>
									<h:commandLink styleClass="link icon" >
										<i class="icon delete"></i>
										<f:ajax execute="@this" render="@form" listener="#{purchaseEditBean.deleteItem(item)}" />
									</h:commandLink>
								</h:column>
		
							</h:dataTable>
								
						</div>	

						<!-- Paid History -->						
						<div class="ui vertical segment">

							<div class="ui header"><i class="icon history"></i> Paid History</div>
							
							<div class="fields">
								
								<div class="field">
									<label>Date</label>
									<h:inputText id="paidDate" p:type="date" converter="#{localDateConverter}" value="#{purchaseEditBean.paid.id.refDate}" />
								</div>
							
								<div class="field">
									<label>Last Remain</label>
									<h:inputText id="paidLastRemain" value="#{purchaseEditBean.paid.lastRemain}" readonly="true" />
								</div>

								<div class="field">
									<label>Paid</label>
									<h:inputText id="paidPaid" value="#{purchaseEditBean.paid.paid}" />
								</div>

								<div class="six wide field">
									<label>Remark</label>
									<h:inputText id="paidRemark" value="#{purchaseEditBean.paid.remark}" />
								</div>

								<!-- Add Button -->
								<div class="field">
									<div class="formButton" />
									<h:commandLink styleClass="ui icon red button" >
										<i class="icon plus"></i>
										<f:ajax execute="paidDate paidLastRemain paidPaid paidRemark" render="@form script messages" listener="#{purchaseEditBean.addPaid()}" />
									</h:commandLink>
								</div>

							</div>
							
							<h:dataTable styleClass="ui table" value="#{purchaseEditBean.paidList}" var="p">
								<h:column>
									<f:facet name="header">
										Paid Date
									</f:facet>
									<h:outputText value="#{p.id.refDate}" converter="#{localDateConverter}" />
								</h:column>

								<h:column>
									<f:facet name="header">
										Last Remain
									</f:facet>
									<h:outputText value="#{p.lastRemain}"  />
								</h:column>

								<h:column>
									<f:facet name="header">
										Paid Anount
									</f:facet>
									<h:outputText value="#{p.paid}"  />
								</h:column>

								<h:column>
									<f:facet name="header">
										Remark
									</f:facet>
									<h:outputText value="#{p.remark}" />
								</h:column>
								
								<h:column>
									<h:commandLink styleClass="link icon" actionListener="#{purchaseEditBean.deletePaid(p)}" >
										<f:ajax execute="@this" render="@form script messages" />
										<i class="icon delete"></i>
									</h:commandLink>
								</h:column>
							</h:dataTable>
						
						</div>
											
						
					</div>
					
					<div class="four wide column">
						<div class="ui vertical segment">
							<div class="ui header"><i class="icon dollar sign"></i> Paid Info</div>
							
							<div class="content">
								
								<!-- Date -->
								<div class="field">
									<label>Invoice Date</label>
									<h:inputText value="#{purchaseEditBean.invoice.refDate}" converter="#{localDateConverter}" p:type="date" >
										<f:ajax execute="@this" render="@this" />							
									</h:inputText>
								</div>

								<!-- Sub Total -->
								<div class="field">
									<label>Sub Total</label>
									<h:inputText readonly="true" value="#{purchaseEditBean.invoice.subTotal}" p:placeholder="Sub Total"/>
								</div>
								
								<!-- Tax -->
								<div class="field">
									<label>Tax</label>
									<h:inputText readonly="true" value="#{purchaseEditBean.invoice.tax}" p:placeholder="Tax"/>
								</div>
							
								<!-- Transportation charges -->
								<div class="field">
									<label>Transportation</label>
									<h:inputText value="#{purchaseEditBean.invoice.transport}" p:placeholder="Transportation Fees">
										<f:ajax execute="@this" render="@this" />
									</h:inputText>
								</div>
								
								<!-- Total -->
								<div class="field">
									<label>Total</label>
									<h:inputText readonly="true" value="#{purchaseEditBean.invoice.total}" p:placeholder="Total"/>
								</div>
							
								<div class="field">
									<label>Paid</label>
									<h:inputText readonly="true" value="#{purchaseEditBean.paidAmount}" p:placeholder="Total"/>
								</div>

								<div class="field">
									<label>Remain</label>
									<h:inputText readonly="true" value="#{purchaseEditBean.remainAmount}" p:placeholder="Total"/>
								</div>
									
								<!-- Save Button -->
								<div class="field">
									<h:commandLink action="#{purchaseEditBean.save()}" styleClass="ui red icon button">
										<i class="icon save outline"></i> Save
									</h:commandLink>
								</div>
							
							
							</div>
						</div>
					</div>
				</div>
			
			
			</h:form>
			
		</ui:define>
	</ui:composition>
</html>